# Generated by Django 4.1 on 2022-08-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
