# Generated by Django 4.1 on 2022-08-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='type_film',
            field=models.TextField(),
        ),
    ]
